name: Build, Test and Release

on: push

jobs:
  build_and_test:
    id: build_and_test
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Node Dependencies
        uses: Borales/actions-yarn@master
        with:
          args: install
      - name: Setup Monorepo Links
        uses: Borales/actions-yarn@master
        with:
          args: setup
      - name: Build Packages
        uses: Borales/actions-yarn@master
        with:
          args: build
      - name: Run Tests
        uses: Borales/actions-yarn@master
        with:
          args: test