name: Build, Test and Release

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  build_test_release:
    name: Build, Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Filter Commit Message
        uses: veggiemonk/skip-commit@1.0.0
        env:
          COMMIT_FILTER: "[skip ci]"

      - name: Rehydrate node_modules/
        uses: actions/download-artifact@1.0.0
        continue-on-error: true
        with:
          name: node_modules-${{ github.sha }}
          path: node_modules

      - name: Rehydrate node_modules/
        uses: actions/download-artifact@1.0.0
        continue-on-error: true
        if: failure()
        with:
          name: node_modules-${{ github.ref }}
          path: node_modules

      - name: Rehydrate .yarn/
        uses: actions/download-artifact@1.0.0
        continue-on-error: true
        with:
          name: yarn_cache-${{ github.sha }}
          path: ~/.yarn

      - name: Rehydrate .yarn/
        uses: actions/download-artifact@1.0.0
        continue-on-error: true
        if: failure()
        with:
          name: yarn_cache-${{ github.ref }}
          path: ~/.yarn

      - name: Install Node Dependencies
        uses: Borales/actions-yarn@1.1.0
        with:
          args: install

      - name: Cache node_modules/
        uses: actions/upload-artifact@1.0.0
        with:
          name: node_modules-${{ github.sha }}
          path: node_modules

      - name: Cache node_modules/
        uses: actions/upload-artifact@1.0.0
        with:
          name: node_modules-${{ github.ref }}
          path: node_modules

      - name: Cache .yarn/
        uses: actions/upload-artifact@1.0.0
        with:
          name: yarn_cache-${{ github.sha }}
          path: ~/.yarn

      - name: Cache .yarn/
        uses: actions/upload-artifact@1.0.0
        with:
          name: yarn_cache-${{ github.ref }}
          path: ~/.yarn

      - name: Setup Monorepo Links
        uses: Borales/actions-yarn@1.1.0
        with:
          args: setup

      - name: Build Packages
        uses: Borales/actions-yarn@1.1.0
        with:
          args: build

      - name: Run Tests
        uses: Borales/actions-yarn@1.1.0
        with:
          args: test

      - name: Release
        uses: Borales/actions-yarn@1.1.0
        if: github.ref == 'refs/heads/master'
        with:
          args: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
