name: Build, Test and Release

on: push

jobs:
  build_test_release:
    name: Build, Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Node Dependencies
        uses: Borales/actions-yarn@1.1.0
        with:
          args: install

      - name: Setup Monorepo Links
        uses: Borales/actions-yarn@1.1.0
        with:
          args: setup

      - name: Build Packages
        uses: Borales/actions-yarn@1.1.0
        with:
          args: build

      - name: Run Tests
        uses: Borales/actions-yarn@1.1.0
        with:
          args: test
          
      - name: Release
        uses: Borales/actions-yarn@1.1.0
        if: github.ref == 'master'
        with:
          args: release