name: Build, Test and Release

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  build_test_release:
    name: Build, Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - id: filter_commit
        name: Filter Commit Message
        uses: veggiemonk/skip-commit@1.0.0
        continue-on-error: true
        env:
          COMMIT_FILTER: "\\[skip ci\\]"

      - name: Install Node Dependencies
        uses: Borales/actions-yarn@1.1.0
        if: job.steps.filter_commit.status == success()
        with:
          args: install

      - name: Setup Monorepo Links
        uses: Borales/actions-yarn@1.1.0
        if: job.steps.filter_commit.status == success()
        with:
          args: setup

      - name: Build Packages
        uses: Borales/actions-yarn@1.1.0
        if: job.steps.filter_commit.status == success()
        with:
          args: build

      - name: Run Tests
        uses: Borales/actions-yarn@1.1.0
        if: job.steps.filter_commit.status == success()
        with:
          args: test

      - name: Release
        uses: Borales/actions-yarn@1.1.0
        if: job.steps.filter_commit.status == success() && github.ref == 'refs/heads/master'
        with:
          args: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
