name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Release
        uses: Borales/actions-yarn@master
        with:
          args: release